import logging
import numpy as np
from sklearn.feature_extraction.text import TfidfVectorizer
import os

logger = logging.getLogger(__name__)

class AIContentDetector:
    """Detects AI-generated content using ML models and pattern analysis"""
    
    def __init__(self):
        self.model = None
        self.vectorizer = TfidfVectorizer(max_features=100)
        self._load_model()
        self.ai_indicators = [
            'as an ai',
            'as a language model',
            'i am an ai',
            'generated by ai',
            'synthetically created',
            'machine learning model',
            'neural network',
        ]
    
    def detect(self, content):
        """Detect if content is AI-generated"""
        try:
            # Multiple detection methods
            pattern_score = self._check_patterns(content)
            entropy_score = self._analyze_entropy(content)
            style_score = self._analyze_writing_style(content)
            
            # Weighted average
            confidence = (pattern_score * 0.3 + entropy_score * 0.3 + style_score * 0.4)
            
            return {
                'content_preview': content[:100],
                'is_ai_generated': confidence > 0.6,
                'confidence': round(confidence, 2),
                'score': round(confidence * 100, 2),
                'analysis': {
                    'pattern_indicators': pattern_score,
                    'entropy_score': entropy_score,
                    'style_analysis': style_score
                },
                'risk_level': self._get_risk_level(confidence)
            }
        
        except Exception as e:
            logger.error(f'Error in AI content detection: {str(e)}')
            return {
                'is_ai_generated': False,
                'confidence': 0.0,
                'error': str(e)
            }
    
    def _check_patterns(self, content):
        """Check for common AI generation patterns"""
        score = 0.0
        content_lower = content.lower()
        
        # Check for AI self-references
        for indicator in self.ai_indicators:
            if indicator in content_lower:
                score += 0.2
        
        # Check for excessive punctuation patterns
        if content.count('...') > 3:
            score += 0.1
        
        # Check for repetitive phrases
        words = content.split()
        if len(words) > 50:
            unique_words = len(set(words))
            repetition_ratio = 1 - (unique_words / len(words))
            if repetition_ratio > 0.3:
                score += 0.15
        
        return min(score, 1.0)
    
    def _analyze_entropy(self, content):
        """Analyze Shannon entropy (randomness) of text"""
        try:
            # Calculate entropy
            from collections import Counter
            char_counts = Counter(content.lower())
            total_chars = len(content)
            
            entropy = 0
            for count in char_counts.values():
                probability = count / total_chars
                entropy -= probability * np.log2(probability)
            
            # Normalize (English text typically 4-5, random: 6-8)
            normalized_entropy = max(0, (entropy - 4) / 4)
            
            return min(normalized_entropy, 1.0)
        
        except Exception as e:
            logger.warning(f'Entropy analysis error: {str(e)}')
            return 0.0
    
    def _analyze_writing_style(self, content):
        """Analyze writing style characteristics"""
        score = 0.0
        
        try:
            # Average sentence length
            sentences = content.split('.')
            if sentences:
                avg_sentence_length = len(content.split()) / len(sentences)
                # AI typically uses consistent, moderate length sentences
                if 10 < avg_sentence_length < 25:
                    score += 0.2
            
            # Check for formal tone indicators
            formal_words = ['furthermore', 'consequently', 'additionally', 'notably', 'importantly']
            for word in formal_words:
                if word in content.lower():
                    score += 0.1
            
            # Check vocabulary diversity
            words = content.split()
            if len(words) > 50:
                unique_ratio = len(set(words)) / len(words)
                # AI tends to have high vocabulary diversity
                if unique_ratio > 0.8:
                    score += 0.2
        
        except Exception as e:
            logger.warning(f'Style analysis error: {str(e)}')
        
        return min(score, 1.0)
    
    def _load_model(self):
        """Load pre-trained ML model (placeholder)"""
        try:
            model_path = 'models/ai_model.pkl'
            if os.path.exists(model_path):
                import pickle
                with open(model_path, 'rb') as f:
                    self.model = pickle.load(f)
                logger.info('AI detection model loaded')
            else:
                logger.warning('AI detection model not found, using pattern-based detection')
        
        except Exception as e:
            logger.warning(f'Error loading model: {str(e)}')
    
    def _get_risk_level(self, confidence):
        """Get risk level based on confidence score"""
        if confidence < 0.3:
            return 'low'
        elif confidence < 0.6:
            return 'medium'
        else:
            return 'high'
